

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:1022581148987:android:487dbb3ed7809780cc3b1e",
      firebase_cli_token: "1//03RYzqv2BA2zTCgYIARAAGAMSNwF-L9IrNHhC4YVwHrXLEPA1q0NsDdoEj-KUwaYaNRJ1nqEgTYT3Oa0H6xHF75I0ZlpXZSI79pw",
     # android_artifact_type:: "Apk",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "ibrahimatef715@gmail.com",
      release_notes: "First Fastlane Firebase Distribution integration"
    )
  end
end